lastUpdated: 2020-06-03
downloadLink: http://www.crisoldecuerda.com/wp-content/uploads/2020/07/PDF-The-Crisol-Book-2020-07-19.pdf

index:
  - title: 20 Years
    author: Seán Wood
    origin: usa
  - title: Ai Hori Begi Ederra
    author: traditional
    origin: eus
  - title: Akkar
    author: Olav L. Mjelva
    origin: swe
  - title: Altsasuko Soka
    author: traditional
    origin: eus
  - title: Ama Euskadi
    author: traditional
    origin: eus
  - title: An Dro Kerfank
    author: Tri Yann
    origin: brt
  - title: Ansuriña
    author: Paulo Nogueira
    origin: gal
  - title: Appropriate Dipstick, The
    author: Phil Cunningham
    origin: sct
  - title: Artikutza
    author: traditional
    origin: eus
  - title: As a Thòiseach
    author: Simon Fraser
    origin: sct
  - title: Astotxo bat Baneuko
    author: traditional
    origin: eus
  - title: Baile de la Manzana
    author: traditional
    origin: cyl
  - title: Ball del Rogle
    author: traditional
    origin: cat
  - title: Ballet de Tortellà
    author: traditional
    origin: cat
  - title: Ball Pla de Tírig
    author: traditional
    origin: val
  - title: Banks of Avonmore, The
    author: traditional
    origin: sct
  - title: Barquito de Vela, Un
    author: Airiños do Parque de Castrelos
    origin: gal
  - title: Beharrezkoa
    author: traditional
    origin: eus
  - title: Big Country
    author: Béla Fleck
    origin: usa
  - title: Bingsjö Lilla Långdans
    author: traditional
    origin: swe
  - title: Blackberry Festival Footrace
    author: David Fisher
    origin: sct
  - title: Blackwater
    author: traditional
    origin: sct
  - title: Blackwater Foot
    author: traditional
    origin: sct
  - title: Bloody Fields of Flanders, The
    author: John MacLellan
    origin: sct
  - title: Blue
    author: Hanneke Cassel
    origin: usa
  - title: Bodas de Cantabrana, Las
    author: traditional
    origin: cyl
  - title: Bolat Dantza
    author: traditional
    origin: eus
  - title: Bourrée de l'Hôpital
    author: traditional
    origin: occ
  - title: Braes of Mar
    author: John Coutis of Deeside
    origin: sct
  - title: Buey, El
    author: traditional
    origin: cyl
  - title: Callum's Road
    author: Donald Shaw
    origin: sct
  - title: Canto de Bembibre
    author: traditional
    origin: gal
  - title: Carrasqueira, A
    author: traditional
    origin: gal
  - title: Cayó la Luna
    author: traditional
    origin: cyl
  - title: Charlie McKerron's Reel
    author: Charlie McKerron
    origin: sct
  - title: Charro del Marinero y la Estrella, El
    author: traditional
    origin: cyl
  - title: Charro Verdadero
    author: traditional
    origin: cyl
  - title: Cigüeña, La
    author: traditional
    origin: cyl
  - title: Contradansa no.7
    author: traditional
    origin: cat
  - title: Corrido de Sepúlveda
    author: traditional
    origin: cyl
  - title: Cozy Ox, The
    author: Olav L. Mjelva
    origin: swe
  - title: Czardas
    author: traditional
    origin: hun
  - title: Danza de Arcos de Miño
    author: traditional
    origin: gal
  - title: Danza de Palitos
    author: traditional
    origin: gal
  - title: Danza de Salceda
    author: traditional
    origin: gal
  - title: David Glen's Jig
    author: David Glen
    origin: sct
  - title: Diana
    author: traditional
    origin: cyl
  - title: Domhnall Dubh
    author: traditional
    origin: sct
  - title: Dulzainero Cojo, El
    author: traditional
    origin: cyl
  - title: Eklunda
    author: traditional
    origin: fin
  - title: Elzic's Farewell
    author: traditional
    origin: usa
  - title: Espatadantza
    author: traditional
    origin: eus
  - title: Espejo, Sol y Luna
    author: traditional
    origin: cyl
  - title: Estrellita
    author: Manuel M. Ponce
    origin: usa
  - title: Eternal Friendship, The
    author: Phil Cunningham
    origin: sct
  - title: Eugene's Tea
    author: Quico Pugés
    origin: cat
  - title: Ewe Wi' The Crookit Horn, The
    author: traditional
    origin: sct
  - title: Falken
    author: Quico Pugés
    origin: cat
  - title: Fandango
    author: traditional
    origin: and
  - title: Fanfarie
    author: traditional
    origin: bal
  - title: Father John Angus Rankin
    author: traditional
    origin: sct
  - title: Fia Na Roca
    author: traditional
    origin: gal
  - title: Fiddle Lint Ball
    author: Galen Fraser
    origin: usa
  - title: Fisterra
    author: traditional
    origin: gal
  - title: Foliada de Soutelo
    author: traditional
    origin: gal
  - title: Foliada do Quinteiro
    author: Xulio Amado Silva
    origin: gal
  - title: Forró Nascente
    author: traditional
    origin: bra
  - title: Forró no Sitio
    author: traditional
    origin: bra
  - title: Foxtrot de Algora
    author: traditional
    origin: cyl
  - title: Freedom Come All Ye
    author: John MacLellan
    origin: sct
  - title: Galbide
    author: traditional
    origin: eus
  - title: Hai Chiki Chiki
    author: traditional
    origin: hun
  - title: Hakbergs Schottis
    author: Carl Aron Hakberg
    origin: swe
  - title: Haurtxo Polita
    author: Gabriel Olaizola
    origin: eus
  - title: Hector, The Hero
    author: James Scott Skinner
    origin: sct
  - title: Hegi
    author: traditional
    origin: eus
  - title: Hörde jag Tønder
    author: Anna Lindblad
    origin: swe
  - title: Iluntzean
    author: Maixa eta Itziar
    origin: eus
  - title: Jack Daniel's
    author: John Morris Rankin
    origin: sct
  - title: Jerusalem Ridge
    author: Kenny Baker
    origin: cbr
  - title: John Cheap, The Chapman
    author: Nathaniel Gow
    origin: sct
  - title: Josefin's Waltz
    author: Roger Tallroth
    origin: swe
  - title: Jota de Montrove
    author: Miguel L. Paradela
    origin: gal
  - title: Jota de Rañín
    author: Pepín Banzo
    origin: ara
  - title: Jota Olé
    author: traditional
    origin: val
  - title: Joy of Julie
    author: Galen Fraser
    origin: usa
  - title: Keep it up!
    author: Simon Fraser
    origin: sct
  - title: Kelburn Brewer, The
    author: Alasdair Fraser
    origin: sct
  - title: Kilts on Fire
    author: Howie MacDonald
    origin: cbr
  - title: Kiwi Reel, The
    author: Willie Hunter
    origin: sct
  - title: Klappvalsen
    author: Mats Edén
    origin: swe
  - title: Korostietako
    author: traditional
    origin: eus
  - title: Kost ar Choad
    author: traditional
    origin: brt
  - title: Långdans från Sollerön
    author: traditional
    origin: swe
  - title: Lantzeko Zortzikoa
    author: traditional
    origin: eus
  - title: Las Habas de Bercero
    author: traditional
    origin: cyl
  - title: Lass That Made the Bed for Me, The
    author: traditional
    origin: sct
  - title: Loriak Udan Intza Bezela
    author: traditional
    origin: eus
  - title: Love Boat
    author: Olav L. Mjelva
    origin: swe
  - title: Luna Sobre Crisol, La
    author: Galen Fraser
    origin: cyl
  - title: Madalenara
    author: traditional
    origin: eus
  - title: Maitia nun Zira
    author: José Tomás Uruñuela
    origin: eus
  - title: Marcha para Santa Ana
    author: traditional
    origin: cyl
  - title: Matins de Bonny Doon, Les
    author: André MArchand
    origin: qbc
  - title: Mazurca de l'Impasse
    author: Gilles Chabenat
    origin: fra
  - title: Megan & Jarrod's Waltz
    author: Natalie Haas
    origin: usa
  - title: Menina Amanhã de Manhã
    author: Tom Zé
    origin: bra
  - title: Metsän Puita Tuuli Tuudittaa
    author: traditional
    origin: fin
  - title: Miñas Cousas, As
    author: traditional
    origin: gal
  - title: Mocita, La
    author: traditional
    origin: cyl
  - title: Mornings at Bonny Doon
    author: André MArchand
    origin: qbc
  - title: Mudanza de Chañe
    author: traditional
    origin: cyl
  - title: Muñeira de Fonsagrada
    author: traditional
    origin: gal
  - title: Muñeira de Fonsagrada
    author: traditional
    origin: gal
  - title: Muñeira Ribeirana
    author: traditional
    origin: gal
  - title: Myra's Jig
    author: Ian Lowthian
    origin: sct
  - title: Mysoxen
    author: Olav L. Mjelva
    origin: swe
  - title: Napkin Tune, The
    author: Rodney Miller
    origin: usa
  - title: Neska Zaharrak
    author: traditional
    origin: eus
  - title: Never Tell Me the Odds
    author: Galen Fraser
    origin: usa
  - title: North Beat
    author: Ethan Lewis
    origin: sct
  - title: No Voy Solo, No
    author: traditional
    origin: gal
  - title: O! Dem Golden Slippers
    author: traditional
    origin: usa
  - title: Off with you!
    author: Simon Fraser
    origin: sct
  - title: Ont Anarem Gardar
    author: traditional
    origin: occ
  - title: On the Wings of a Skorrie
    author: Michael Ferrie
    origin: sct
  - title: Ook Pik Waltz
    author: Frankie Rodgers
    origin: usa
  - title: O' Pingacho
    author: traditional
    origin: prt
  - title: Ovo, O
    author: Hermeto Pascoal
    origin: bra
  - title: Pasacalles de Carpio de Tajo
    author: traditional
    origin: cyl
  - title: Pas del Lop, Lo
    author: traditional
    origin: occ
  - title: Pasodoble Morellano
    author: traditional
    origin: gal
  - title: Peerie Weerie, The
    author: traditional
    origin: sct
  - title: Pericón de los Talaos
    author: Repertorio de Los Talaos
    origin: cyl
  - title: Periquito, El
    author: traditional
    origin: ven
  - title: Perrie Werrie
    author: traditional
    origin: sct
  - title: Pirrie Wirrie
    author: traditional
    origin: sct
  - title: Polonäs från Sexdrega
    author: traditional
    origin: swe
  - title: Polska efter Nylandspojkarna
    author: traditional
    origin: swe
  - title: Polska efter Svedin
    author: traditional
    origin: swe
  - title: Ramnee Ceilidh
    author: Gordon Duncan
    origin: sct
  - title: Reel for Carl
    author: Jerry Holland
    origin: cbr
  - title: Regina Stubbert
    author: Brenda Stubbert
    origin: cbr
  - title: Remember Blake
    author: Jeremy Kittel
    origin: usa
  - title: Ride the Wild Turkey
    author: Darol Anger
    origin: usa
  - title: Rob Roy MacGregor
    author: Simon Fraser
    origin: sct
  - title: Ronda de Carballeda
    author: traditional
    origin: cyl
  - title: Rondador Desesperado
    author: traditional
    origin: cyl
  - title: Rumba del Topo
    author: traditional
    origin: cyl
  - title: Rumba de Malpica
    author: traditional
    origin: gal
  - title: Saka
    author: traditional
    origin: eus
  - title: Sape que Sape
    author: traditional
    origin: cyl
  - title: Sardana del Ball de Cavallets de Sant Feliu de Pallerols
    author: traditional
    origin: cat
  - title: Scarce O'Tatties
    author: John Morris Rankin
    origin: sct
  - title: Seguidillas Manchegas
    author: traditional
    origin: cyl
  - title: Shepherdess, The
    author: traditional
    origin: sct
  - title: Show Me
    author: Catriona MacDonald
    origin: sct
  - title: Siete por Ocho
    author: traditional
    origin: cyl
  - title: Sister Jean
    author: traditional
    origin: sct
  - title: Si Supiera que Cantando…
    author: traditional
    origin: cyl
  - title: Sleeping Tune, The
    author: Gordon Duncan
    origin: sct
  - title: Stan Chapman's
    author: Jerry Holland
    origin: cbr
  - title: Talon's Trip to Thompson Island
    author: Kevin Henderson
    origin: sct
  - title: Tarbolton Lodge
    author: traditional
    origin: sct
  - title: Theme for sct
    author: Alasdair Fraser
    origin: sct
  - title: TIDGA
    author: Hanneke Cassel
    origin: usa
  - title: Tonder… The Eternal Friendship
    author: Phil Cunningham
    origin: sct
  - title: Tony Bliar's Reel
    author: Adam Sutherland
    origin: sct
  - title: Tortolita, La
    author: traditional
    origin: cyl
  - title: Tourment, Le
    author: Jean-Paul Loyer
    origin: qbc
  - title: Tralala
    author: traditional
    origin: swe
  - title: Trenzinho do Caipiro
    author: traditional
    origin: bra
  - title: Trilhos Urbanos
    author: Caetono Verloso
    origin: bra
  - title: Trollet i Skäten
    author: Johan von Schwartz
    origin: swe
  - title: Troll in the Knitting Machine, The
    author: Johan von Schwartz
    origin: swe
  - title: Txikitxuterik
    author: traditional
    origin: eus
  - title: Un Kukurutxu
    author: Quico Pugés
    origin: cat
  - title: Unnamed tune
    author: traditional
    origin: sct
  - title: Vai
    author: Tom Zé
    origin: bra
  - title: Venjan
    author: Anders Hall
    origin: swe
  - title: Vida Mía, La
    author: traditional
    origin: cyl
  - title: Vou Veri-vou
    author: traditional
    origin: mal
  - title: Vrålkåda
    author: Roger Tallroth
    origin: swe
  - title: War Hent Kerrigouarch
    author: Soïc Siberil
    origin: brt
  - title: Warlock, The
    author: Robert Lowe
    origin: sct
  - title: Wedding March
    author: traditional
    origin: swe
  - title: Wee Man from Uist, The
    author: traditional
    origin: sct
  - title: Whitewater
    author: Alasdair Fraser
    origin: sct
  - title: Willie's Trip to Toronto
    author: Jerry Holland
    origin: cbr
  - title: Xota de Paradela
    author: Miguel López Paradela
    origin: gal
  - title: Ya Pasó el Río
    author: traditional
    origin: cyl
  - title: Zortzikoa
    author: traditional
    origin: eus
